language: bash
os:
  - osx
env:
  - FLUTTER_CHANNEL="stable"
  - FLUTTER_CHANNEL="master"
sudo: false
before_script:
  - cd ..
  - git clone https://github.com/flutter/flutter.git -b $FLUTTER_CHANNEL
  - export PATH=$PATH:$PWD/flutter/bin:$PWD/flutter/bin/cache/dart-sdk/bin
  - cd -
  - flutter doctor
script:
  - set -e # abort CI if an error happens
  - ./scripts/flutter_test.sh .
  - ./scripts/flutter_test.sh ./example

  # export coverage
  - if [ $FLUTTER_CHANNEL = "master" ]; then
    bash <(curl -s https://codecov.io/bash);
    fi
matrix:
  fast_finish: true
  allow_failures:
    # stable doesn't have debugDoingBuild yet
  - env: FLUTTER_CHANNEL="stable"
cache:
  directories:
    - $HOME/.pub-cache
