name: provider
description: A mixture between dependency injection and state management, built with widgets for widgets.
version: 3.0.0+2
homepage: https://github.com/rrousselGit/provider
authors:
  - Remi Rousselet <darky12s@gmail.com>
  - Flutter Team <flutter-dev@googlegroups.com>

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.4.0
  mockito: ^4.0.0
  flutter_test:
    sdk: flutter
