name: provider
description: A mixture between dependency injection and state management, built with widgets for widgets.
version: 4.0.0
homepage: https://github.com/rrousselGit/provider
authors:
  - Remi Rousselet <darky12s@gmail.com>
  - Flutter Team <flutter-dev@googlegroups.com>

environment:
  sdk: '>=2.2.2 <3.0.0'
  flutter: '>= 1.12.1'

dependencies:
  flutter:
    sdk: flutter
  nested: '>= 0.0.4 < 2.0.0'

dev_dependencies:
  mockito: ^4.0.0
  flutter_test:
    sdk: flutter
